spring:
  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: quantum.research.assistant@gmail.com
    password: pltojqffmlatlncf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
